// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvixvtucszfjfunjewau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2aXh2dHVjc3pmamZ1bmpld2F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMzcxNzQsImV4cCI6MjA2ODgxMzE3NH0.EmTJqnagMDWc4OgWpCbg7RvT_2ou3Zo9lAaoMpWkQLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});